---
title: "Get started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval     = FALSE,
  echo     = TRUE,
  comment  = "#>"
)
```


## Skeleton



```{r setup}
# Setup ----
library("forcis")
```



```{r 'to-develop'}
# Define the path to store data ----
# path       <- here::here()

# Download the latest version of FORCIS database (from Zenodo) ----
get_forcis_db(path = path)

# Import net data ----
nets <- get_plankton_nets_data(path)

# Select taxonomy ----
nets <- select_taxonomy(nets, taxonomy = "OT")

# Select columns ----
nets <- select_columns(nets, cols = NULL)

# Compute concentration ----
nets_concentrations <- compute_concentrations(nets, aggregate = TRUE)

# Compute frequencies ----
nets_frequencies <- compute_frequencies(nets, aggregate = TRUE)

# Compute abundances ----
nets_abundances <- compute_abundances(nets, aggregate = TRUE)
```
